
name: Generate a snake game

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update commits in snake game
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: celsodias12
          svg_out_path: dist/github-contribution-grid-snake.svg
